modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dragon_it_out"
version="1.0.0"
displayName="Dragon_it_out"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="atwst, MCreator"

[[dependencies.dragon_it_out]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




